# Generated by Django 3.0.7 on 2020-07-10 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200627_0235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='owner',
        ),
    ]
