# Generated by Django 3.0.7 on 2020-06-23 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='title',
            field=models.CharField(max_length=240),
        ),
    ]
